### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by JMSCompSci** [ADA-SITE/code-org-student-progress-scraper#1]
I saved the webpage in two parts.  I saved them both to the progress_files directory.  I tried firefox and chrome.  I only receive errors.

C:\Users\twright\Downloads\scraper>python solver.py "Wright - 2ND Period - Programming 1"
Processing code.org results...
->Processing user progress...
->Processing progress file: ./progress_files\.keep...
Traceback (most recent call last):
  File "C:\Users\twright\Downloads\scraper\solver.py", line 222, in <module>
    generateUserProgressReport()
  File "C:\Users\twright\Downloads\scraper\solver.py", line 180, in generateUserProgressReport
    userProgress = processCodeOrgData()
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\twright\Downloads\scraper\solver.py", line 166, in processCodeOrgData
    userIdToProgress.update(__getUserIdToProgressMapping(path))
TypeError: 'NoneType' object is not iterable

**Comment by JMSCompSci** [comment]
Update.  I was able to get it working by deleting the ".keep" file.  And making sure there were ONLY HTML files in the "progress_files" folder.  No other folders.
